# Generated by Django 3.2.18 on 2023-02-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Укажите адресс секции', max_length=200, unique=True, verbose_name='Адресс секции')),
                ('top_section', models.ForeignKey(blank=True, default=None, help_text='Укажите родительскую секцию', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_sections', to='tree.section', verbose_name='Родительская секция')),
            ],
        ),
    ]
