# Generated by Django 3.2.18 on 2023-02-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='main_menu', help_text='Укажите адресс меню', max_length=200, unique=True, verbose_name='Адресс меню'),
            preserve_default=False,
        ),
    ]
