# Generated by Django 3.2.18 on 2023-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_section_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='adress',
            field=models.CharField(blank=True, help_text='Укажите адресс секции без /', max_length=200, unique=True, verbose_name='Адресс секции'),
        ),
    ]
