# Generated by Django 3.2.18 on 2023-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_alter_section_adress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='Укажите название', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Укажите человекочитаемое имя секции меню.', max_length=200, verbose_name='Название'),
        ),
    ]
