# Generated by Django 3.2.18 on 2023-02-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20230226_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='adress',
            field=models.CharField(blank=True, help_text='Укажите адресс секции без /', max_length=200, verbose_name='Адресс секции'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'menu'), name='name_menu'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('adress', 'menu'), name='adress_menu'),
        ),
    ]
