# Generated by Django 3.2.18 on 2023-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20230227_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='adress',
            field=models.CharField(help_text='Укажите адресс секции без /', max_length=200, verbose_name='Адресс секции'),
        ),
    ]
